application: spa
version: 1
runtime: go
api_version: go1

handlers:
# Handler for dart packages
- url: /packages
  static_dir: web/packages

# All other requests are handled by the Go code
- url: /.*
  script: _go_app
  secure: always

